package org.apache.rya.indexing.pcj.fluo.app.export;
import org.apache.rya.api.domain.RyaSubGraph;
import org.apache.rya.indexing.pcj.fluo.app.export.IncrementalBindingSetExporter.ResultExportException;

/**
 * Incrementally exports RyaSubGraphs that are generated by SPARQL Construct Queries
 * from the Rya-Fluo application to the core Rya tables.
 *
 */
public interface IncrementalRyaSubGraphExporter extends AutoCloseable {

    /**
     * Export a RyaSubGraph that is the result of SPARQL Construct Query.
     *
     * @param constructID - The Fluo Id of the construct query the created the RyaSubGraph
     * @param subgraph - The RyaSubGraph to export (non-null)
     * @throws ResultExportException The result could not be exported.
     */
    public void export(String constructID, RyaSubGraph subgraph) throws ResultExportException;
    
}
